name: GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - valaxy

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4   # 升级到 v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # 升级到 v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'  # 加缓存，构建更快

      - name: 📦 Install Dependencies
        run: pnpm i

      - name: 🌌 Build Valaxy Blog
        run: pnpm build

      - name: 🪤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # 升级到 v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
